### ISSUE TITLE
MinLog dependent on lodash, moment and moment-timezone

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/minlog#14]
Is it really "Min" after that?

**Comment by andreineculau** [comment]
yes, interface-wise (minlog does has a super simple flow with no surprises, no convenience gimmicks, that allow for any conceivable setup)
and probably relative-wise as well - e.g. bunyan has dtrace for instance, many have terminal color handling, etc

ps: tangentially related https://github.com/tobiipro/minlog/tree/f/anu-dayjs and I don't think timezone handling is vital. And then we're left with lodash-firecloud which will stay
